### ISSUE TITLE
Need updated for 0.9.0

### ISSUE THREAD

**Issue by ryw** [arunoda/meteor-streams#21]

**Comment by rhyslbw** [comment]
@arunoda I think a public announcement for maintainers is the best thing for this project. It looks like a great tool

**Comment by alexzaporozhets** [comment]
Any update on this issue?

**Comment by ncubica** [comment]
This is really great project I'm being using it does anybody knows if somebody is keeping maintaining this or have a fork?

**Comment by Lepozepo** [comment]
Hi @ncubica, I have a fork of this project that seems to work but I haven't reviewed the code in a while. Look for `lepozepo:streams` in atmosphere. ^_^ If there are any issues let me know and I'll try to get to them as soon as I get a chance.

**Comment by rhyslbw** [comment]
Also check out https://github.com/raix/Meteor-EventDDP. There's an [open PR](https://github.com/raix/Meteor-EventDDP/pull/1) for server to server

**Comment by cguinnup** [comment]
Shouldn't the inactive status be referenced on the project documentation website?  Googling "meteor websockets" still lists http://arunoda.github.io/meteor-streams/ in the top results.

**Comment by derwaldgeist** [comment]
+1

It's quite sad that this repo is not maintained anymore. Are there any better alternatives?

I really like the blackboard app built on top of it, and the ebook still does not mention that this package is deprecated.

**Comment by mitar** [comment]
I think the best would be to get this in the core: https://github.com/meteor/meteor/issues/5645

**Comment by derwaldgeist** [comment]
@mitar Yes, definitely. But as long as this has not happened, I would love to see any alternative.

**Comment by mitar** [comment]
I think the future is to replace Websockets with WebRTC and then we can have native support for data streams and this package would not really be needed anymore. I wrote those ideas [here](https://github.com/MeteorCommunity/discussions/issues/77).

**Comment by derwaldgeist** [comment]
Yes, I was thinking about this myself, because I am already using WebRTC for video transmission. The problem is that WebRTC is not supported in many browsers. I can use it, because my main target is mobile - and there I can use Cordova plugins for achieving this. But on the web, I am restricted to Chrome and Firefox at the moment.

**Comment by mitar** [comment]
Yes, but I think the main mental shift is to see server simply as another WebRTC peer. Then everything becomes much simpler to think. :-)

**Comment by derwaldgeist** [comment]
Yes, definitely! It would be great if this would be added. A peer-to-peer data channel would be awesome. May I ask which WebRTC backend service you are using at the moment in combination with Meteor? I am using OpenTok at the moment, since there was a Cordova plugin for it, but that plugin is unmaintained and rather buggy. I would also prefer a service that is not charging on a per-minute basis. Or did you set your servers up yourself?

**Comment by mitar** [comment]
I tend to set up the servers myself. By I do not use WebRTC because I needed server-side MediaStream support which I have not found (at least not in an open source implementation).

**Comment by derwaldgeist** [comment]
Ok, thanks.
